version: '3'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
       - "80:80/tcp"
       - "443:443/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    environment:
      - HETZNER_API_KEY=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.net`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=hetzner"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=example.net"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.example.net"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=traefik:{SHA}<generate secret>"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-secure.headers.framedeny=true"
      - "traefik.http.middlewares.traefik-secure.headers.browserxssfilter=true"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=http"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"


  whoami:
    image: "traefik/whoami"
    restart: unless-stopped
    network_mode: bridge
    deploy:
      mode: replicated
      replicas: 10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.net`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.middlewares.whoami.headers.framedeny=true"
      - "traefik.http.middlewares.whoami.headers.browserxssfilter=true"
      - "traefik.http.middlewares.whoami.redirectscheme.scheme=https"
      - "traefik.http.middlewares.whoami.redirectscheme.permanent=true"